# Generated by Django 3.2.25 on 2024-09-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_resumes_delete_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='name6',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='resumes',
            name='name7',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='resumes',
            name='name8',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='resumes',
            name='name9',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
