# Generated by Django 3.2.25 on 2024-09-13 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20240913_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='abouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name0', models.CharField(default='test', max_length=100)),
                ('name1', models.CharField(default='test', max_length=100)),
                ('name2', models.CharField(default='test', max_length=100)),
                ('name3', models.CharField(default='test', max_length=100)),
                ('name4', models.CharField(default='test', max_length=100)),
                ('name5', models.CharField(default='test', max_length=100)),
                ('name6', models.CharField(default='test', max_length=100)),
                ('name7', models.CharField(default='test', max_length=100)),
                ('name8', models.CharField(default='test', max_length=100)),
                ('name9', models.CharField(default='test', max_length=100)),
                ('scheduled', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(default='test')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='resumes',
            name='name6',
        ),
        migrations.RemoveField(
            model_name='resumes',
            name='name7',
        ),
        migrations.RemoveField(
            model_name='resumes',
            name='name8',
        ),
        migrations.RemoveField(
            model_name='resumes',
            name='name9',
        ),
    ]
