# Generated by Django 3.2.25 on 2024-09-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_auto_20240913_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='abouts',
            new_name='About',
        ),
        migrations.RenameModel(
            old_name='Resumes',
            new_name='Resume',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
