# Generated by Django 3.2.25 on 2024-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_auto_20240913_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name12',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
