# Generated by Django 4.2 on 2024-09-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_about_name12'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='name10',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name11',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name12',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name6',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name7',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name8',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name9',
        ),
    ]
