# Generated by Django 4.2 on 2024-09-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_contact_remove_about_name10_remove_about_name11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name10',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='name11',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='name12',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='name3',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='name4',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='name5',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='name6',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='name7',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='name8',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='name9',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
