# Generated by Django 4.2 on 2024-09-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_contactformsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormSubmission',
        ),
        migrations.AddField(
            model_name='service',
            name='Description_content',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='service',
            name='Edelectus_content',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='service',
            name='Feature_content',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='service',
            name='Temporibus_content',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='service',
            name='about_content',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services.jpg', upload_to='services'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_servise',
            field=models.CharField(default='Default Service Name', max_length=100),
        ),
    ]
