# Generated by Django 4.2 on 2024-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_delete_contactformsubmission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Edelectus_content',
            new_name='Description_content_Description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Description_content',
            new_name='Description_content_name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Temporibus_content',
            new_name='Edelectus_content_Description',
        ),
        migrations.AddField(
            model_name='service',
            name='Edelectus_content_name',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='service',
            name='Temporibus_content_Description',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='service',
            name='Temporibus_content_name',
            field=models.TextField(default='test'),
        ),
    ]
